### ISSUE TITLE
Add ranktest into Stata package requirement

### ISSUE THREAD

**Issue by ledwindra** [adviksh/when-guidance-changes#1]
Good day @adviksh,

Lukman here. First of all, I would like to say thank you for making this repository publicly available. Secondly, this is totally amazing! It works really well. Check out my [package](https://github.com/marketplace/actions/stata-action) to run Stata remotely using GitHub Actions. Your paper is the first that compiles properly in my workflow among many candidates here on GitHub.

Only one thing though: you may want to add `ranktest` into Stata package requirement in the README because it seemed to be missing when I ran the code initially.

Thanks once again!

Best regards

**Comment by adviksh** [comment]
Hi Lukman,

Thank you for taking the time to run our code! We're glad to know our replication materials are useful. 

Thanks as well for letting us know about the `ranktest` dependency—I've just added it to the README.

Best wishes,
Advik (and Charlie and Pierre-Luc)
